metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"
replication_factor = 1

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "garage-deu1:3901"
rpc_secret = "c7f0df4bd6b1efd4b8f1adce68e4e0f96b7fea08ad3eb26ca83bc8c77df22d3d"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = ".s3.garage.localhost"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token = "vetchium-dev-admin-token"
